# Generated by Django 2.2 on 2019-04-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('solution', models.ForeignKey(on_delete=None, to='core.Solution')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('typeName', models.CharField(max_length=30)),
                ('entityModel', models.ForeignKey(on_delete=None, to='core.EntityModel')),
            ],
        ),
    ]
