# Generated by Django 2.2 on 2019-05-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migration',
            name='date_executed',
            field=models.DateTimeField(null=True),
        ),
    ]
