# Generated by Django 2.2 on 2019-08-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='meta_instance_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='started_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
