# Generated by Django 2.2 on 2019-05-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190508_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='migration',
            name='first',
            field=models.BooleanField(default=False),
        ),
    ]
