# Generated by Django 2.2 on 2019-04-12 22:41

from django.db import migrations

class Migration(migrations.Migration):
    """
     Non-Atomic is necessary here. Renaming the 'core_entitymodel' table while in a transaction 
     is not supported on SQLite < 3.26 because it would break referential integrity.
    """
    atomic = False
    dependencies = [
        ('core', '0002_entitymodel_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntityModel',
            new_name='Entity',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='entityModel',
            new_name='entity',
        ),
    ]
