# Generated by Django 2.2 on 2019-05-24 01:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190523_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[(core.models.FIELD_TYPES('char'), 'char'), (core.models.FIELD_TYPES('bool'), 'bool'), (core.models.FIELD_TYPES('int'), 'int'), (core.models.FIELD_TYPES('dec'), 'dec'), (core.models.FIELD_TYPES('timestamp'), 'timestamp'), (core.models.FIELD_TYPES('UUID'), 'UUID'), (core.models.FIELD_TYPES('SERIAL'), 'SERIAL')], max_length=12),
        ),
    ]
