# Generated by Django 2.2 on 2019-12-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191212_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='container',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='technology',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
