# Generated by Django 2.2 on 2019-04-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190412_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='typeName',
        ),
    ]
