# Generated by Django 2.2 on 2019-12-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191217_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
