# Generated by Django 2.2 on 2019-04-15 17:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_field_typename'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[(core.models.FIELD_TYPES('char'), 'char'), (core.models.FIELD_TYPES('bool'), 'bool'), (core.models.FIELD_TYPES('int'), 'int'), (core.models.FIELD_TYPES('dec'), 'dec')], default='char', max_length=4),
            preserve_default=False,
        ),
    ]
