# Generated by Django 2.2 on 2019-06-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190524_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
