# Generated by Django 2.2 on 2019-04-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_field_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='entity',
            field=models.ForeignKey(on_delete=None, related_name='fields', to='core.Entity'),
        ),
    ]
