# Generated by Django 2.2 on 2019-06-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190603_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='table',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
