# Generated by Django 2.2 on 2019-04-17 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190415_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='solution',
            field=models.ForeignKey(on_delete=None, related_name='apps', to='core.Solution'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='solution',
            field=models.ForeignKey(on_delete=None, related_name='entities', to='core.Solution'),
        ),
        migrations.AlterField(
            model_name='field',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.Entity'),
        ),
    ]
