# Generated by Django 2.2 on 2019-12-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191217_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='process_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddConstraint(
            model_name='appversion',
            constraint=models.UniqueConstraint(fields=('process_id',), name='unique_app_process_id'),
        ),
    ]
