# Generated by Django 2.2 on 2020-02-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191219_1946'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appversion',
            name='unique_app_process_id',
        ),
        migrations.AddField(
            model_name='solution',
            name='is_reprocessing',
            field=models.BooleanField(default=False),
        ),
    ]
