# Generated by Django 2.2 on 2020-02-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191219_1946'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appversion',
            name='unique_app_process_id',
        ),
    ]
