# Generated by Django 2.2 on 2019-06-07 21:01

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_filter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filter',
            new_name='MapFilter',
        ),
        migrations.CreateModel(
            name='MapFilterParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('field_type', models.CharField(choices=[(core.models.FIELD_TYPES('char'), 'char'), (core.models.FIELD_TYPES('bool'), 'bool'), (core.models.FIELD_TYPES('int'), 'int'), (core.models.FIELD_TYPES('dec'), 'dec'), (core.models.FIELD_TYPES('timestamp'), 'timestamp'), (core.models.FIELD_TYPES('UUID'), 'UUID'), (core.models.FIELD_TYPES('SERIAL'), 'SERIAL')], max_length=12)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='core.MapFilter')),
            ],
        ),
    ]
