# Generated by Django 2.2 on 2020-02-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200205_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_reprocessable',
            field=models.BooleanField(default=False),
        ),
    ]
