# Generated by Django 2.2 on 2020-03-18 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_solution_is_reprocessable'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymap',
            name='app_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='core.AppVersion'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='entitymap',
            unique_together={('app_version', 'name')},
        ),
        migrations.RemoveField(
            model_name='entitymap',
            name='app',
        ),
    ]
