# Generated by Django 2.2 on 2019-06-10 21:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mapfilter_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.Solution')),
            ],
        ),
    ]
