# Generated by Django 2.2 on 2019-04-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_entitymap_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
