# Generated by Django 2.2 on 2019-04-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_entity_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
