# Generated by Django 2.2 on 2020-04-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200318_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
