# Generated by Django 2.2 on 2019-04-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_field_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='field',
            name='created_at',
        ),
        migrations.AddField(
            model_name='entity',
            name='migration',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='migration',
            field=models.UUIDField(null=True),
        ),
    ]
