# Generated by Django 2.2 on 2020-04-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_appversion_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='is_reprocessable',
            field=models.BooleanField(default=True),
        ),
    ]
