# Generated by Django 2.2 on 2019-06-24 15:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_field_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[(core.models.FIELD_TYPES('char'), 'char'), (core.models.FIELD_TYPES('varchar'), 'varchar'), (core.models.FIELD_TYPES('text'), 'text'), (core.models.FIELD_TYPES('bool'), 'bool'), (core.models.FIELD_TYPES('int'), 'int'), (core.models.FIELD_TYPES('dec'), 'dec'), (core.models.FIELD_TYPES('timestamp'), 'timestamp'), (core.models.FIELD_TYPES('UUID'), 'UUID'), (core.models.FIELD_TYPES('SERIAL'), 'SERIAL')], max_length=12),
        ),
        migrations.AlterField(
            model_name='mapfilterparameter',
            name='field_type',
            field=models.CharField(choices=[(core.models.FIELD_TYPES('char'), 'char'), (core.models.FIELD_TYPES('varchar'), 'varchar'), (core.models.FIELD_TYPES('text'), 'text'), (core.models.FIELD_TYPES('bool'), 'bool'), (core.models.FIELD_TYPES('int'), 'int'), (core.models.FIELD_TYPES('dec'), 'dec'), (core.models.FIELD_TYPES('timestamp'), 'timestamp'), (core.models.FIELD_TYPES('UUID'), 'UUID'), (core.models.FIELD_TYPES('SERIAL'), 'SERIAL')], max_length=12),
        ),
    ]
