# Generated by Django 2.2 on 2020-05-12 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200416_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reprocess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('reprocess_instance_id', models.UUIDField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_reprocessing', models.BooleanField(null=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprocesses', to='core.Solution')),
            ],
        ),
    ]
