# Generated by Django 2.2 on 2020-04-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200416_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='disabled',
            field=models.DateTimeField(null=True),
        ),
    ]
