# Generated by Django 2.2 on 2020-06-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_reproduction'),
        ('core', '0013_branch_disabled'),
    ]

    operations = [
    ]
